//! Country-related types.



//		Packages

use crate::{
	currency::CurrencyCode,
	language::LanguageCode,
};
use core::{
	fmt::{Display, self},
	str::FromStr,
};
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use utoipa::ToSchema;



//		Enums

//		CountryCode																
/// The possible countries' codes.
/// 
/// These codes are based on the ISO 3166 standard, specifically ISO 3166-1,
/// which defines codes of two and three characters to represent countries and
/// territories. There are both alphabetic and numeric codes, using either two
/// letters, three letters, or three numbers.
/// 
/// # Alphabetic codes
/// 
/// The alphabetic codes are defined by the ISO 3166-1 alpha-2 set, which is the
/// most widely-used of the three sets; and the ISO 3166-1 alpha-3 set, which is
/// less widely-used but gives better visual association between the codes and
/// country names than the alpha-2 set.
/// 
/// # Numeric codes
/// 
/// The three-digit numeric code is a useful alternative when the letter-based
/// code may not be appropriate.
/// 
/// # Data sources
/// 
/// The list of codes is available from [the ISO site](https://www.iso.org/iso-3166-country-codes.html),
/// and from [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1).
/// 
/// # See also
/// 
/// * [`Country`]
/// 
#[cfg_attr(    feature = "reasons",  allow(clippy::upper_case_acronyms, reason = "Uppercase is suitable here"))]
#[cfg_attr(not(feature = "reasons"), allow(clippy::upper_case_acronyms))]
#[cfg_attr(    feature = "reasons",  allow(clippy::zero_prefixed_literal, reason = "Zeroes aid readability here"))]
#[cfg_attr(not(feature = "reasons"), allow(clippy::zero_prefixed_literal))]
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize, ToSchema)]
#[repr(u16)]
#[serde(into = "String", try_from = "String")]
#[non_exhaustive]
pub enum CountryCode {
	//		Two-letter codes (ISO 3166-1 alpha-2)								
	AD  = 020,
	AE  = 784,
	AF  = 004,
	AG  = 028,
	AI  = 660,
	AL  = 008,
	AM  = 051,
	AO  = 024,
	AQ  = 010,
	AR  = 032,
	AS  = 016,
	AT  = 040,
	AU  = 036,
	AW  = 533,
	AX  = 248,
	AZ  = 031,
	BA  = 070,
	BB  = 052,
	BD  = 050,
	BE  = 056,
	BF  = 854,
	BG  = 100,
	BH  = 048,
	BI  = 108,
	BJ  = 204,
	BL  = 652,
	BM  = 060,
	BN  = 096,
	BO  = 068,
	BQ  = 535,
	BR  = 076,
	BS  = 044,
	BT  = 064,
	BV  = 074,
	BW  = 072,
	BY  = 112,
	BZ  = 084,
	CA  = 124,
	CC  = 166,
	CD  = 180,
	CF  = 140,
	CG  = 178,
	CH  = 756,
	CI  = 384,
	CK  = 184,
	CL  = 152,
	CM  = 120,
	CN  = 156,
	CO  = 170,
	CR  = 188,
	CU  = 192,
	CV  = 132,
	CW  = 531,
	CX  = 162,
	CY  = 196,
	CZ  = 203,
	DE  = 276,
	DJ  = 262,
	DK  = 208,
	DM  = 212,
	DO  = 214,
	DZ  = 012,
	EC  = 218,
	EE  = 233,
	EG  = 818,
	EH  = 732,
	ER  = 232,
	ES  = 724,
	ET  = 231,
	FI  = 246,
	FJ  = 242,
	FK  = 238,
	FM  = 583,
	FO  = 234,
	FR  = 250,
	GA  = 266,
	GB  = 826,
	GD  = 308,
	GE  = 268,
	GF  = 254,
	GG  = 831,
	GH  = 288,
	GI  = 292,
	GL  = 304,
	GM  = 270,
	GN  = 324,
	GP  = 312,
	GQ  = 226,
	GR  = 300,
	GS  = 239,
	GT  = 320,
	GU  = 316,
	GW  = 624,
	GY  = 328,
	HK  = 344,
	HM  = 334,
	HN  = 340,
	HR  = 191,
	HT  = 332,
	HU  = 348,
	ID  = 360,
	IE  = 372,
	IL  = 376,
	IM  = 833,
	IN  = 356,
	IO  = 086,
	IQ  = 368,
	IR  = 364,
	IS  = 352,
	IT  = 380,
	JE  = 832,
	JM  = 388,
	JO  = 400,
	JP  = 392,
	KE  = 404,
	KG  = 417,
	KH  = 116,
	KI  = 296,
	KM  = 174,
	KN  = 659,
	KP  = 408,
	KR  = 410,
	KW  = 414,
	KY  = 136,
	KZ  = 398,
	LA  = 418,
	LB  = 422,
	LC  = 662,
	LI  = 438,
	LK  = 144,
	LR  = 430,
	LS  = 426,
	LT  = 440,
	LU  = 442,
	LV  = 428,
	LY  = 434,
	MA  = 504,
	MC  = 492,
	MD  = 498,
	ME  = 499,
	MF  = 663,
	MG  = 450,
	MH  = 584,
	MK  = 807,
	ML  = 466,
	MM  = 104,
	MN  = 496,
	MO  = 446,
	MP  = 580,
	MQ  = 474,
	MR  = 478,
	MS  = 500,
	MT  = 470,
	MU  = 480,
	MV  = 462,
	MW  = 454,
	MX  = 484,
	MY  = 458,
	MZ  = 508,
	NA  = 516,
	NC  = 540,
	NE  = 562,
	NF  = 574,
	NG  = 566,
	NI  = 558,
	NL  = 528,
	NO  = 578,
	NP  = 524,
	NR  = 520,
	NU  = 570,
	NZ  = 554,
	OM  = 512,
	PA  = 591,
	PE  = 604,
	PF  = 258,
	PG  = 598,
	PH  = 608,
	PK  = 586,
	PL  = 616,
	PM  = 666,
	PN  = 612,
	PR  = 630,
	PS  = 275,
	PT  = 620,
	PW  = 585,
	PY  = 600,
	QA  = 634,
	RE  = 638,
	RO  = 642,
	RS  = 688,
	RU  = 643,
	RW  = 646,
	SA  = 682,
	SB  = 090,
	SC  = 690,
	SD  = 729,
	SE  = 752,
	SG  = 702,
	SH  = 654,
	SI  = 705,
	SJ  = 744,
	SK  = 703,
	SL  = 694,
	SM  = 674,
	SN  = 686,
	SO  = 706,
	SR  = 740,
	SS  = 728,
	ST  = 678,
	SV  = 222,
	SX  = 534,
	SY  = 760,
	SZ  = 748,
	TC  = 796,
	TD  = 148,
	TF  = 260,
	TG  = 768,
	TH  = 764,
	TJ  = 762,
	TK  = 772,
	TL  = 626,
	TM  = 795,
	TN  = 788,
	TO  = 776,
	TR  = 792,
	TT  = 780,
	TV  = 798,
	TW  = 158,
	TZ  = 834,
	UA  = 804,
	UG  = 800,
	UM  = 581,
	US  = 840,
	UY  = 858,
	UZ  = 860,
	VA  = 336,
	VC  = 670,
	VE  = 862,
	VG  = 092,
	VI  = 850,
	VN  = 704,
	VU  = 548,
	WF  = 876,
	WS  = 882,
	YE  = 887,
	YT  = 175,
	ZA  = 710,
	ZM  = 894,
	ZW  = 716,
	//		Three-letter codes (ISO 3166-1 alpha-3)								
	//	For maximum ease of use, both two-letter and three-letter codes are
	//	stored in the same enum. However, this causes a collision between the
	//	numeric representations. To avoid this, the three-letter codes have
	//	1,000 added to them, for the sole purpose of internal storage. This
	//	gets adjusted when the enum variants are serialized or otherwise
	//	represented as an integer.
	ABW = 1_533,
	AFG = 1_004,
	AGO = 1_024,
	AIA = 1_660,
	ALA = 1_248,
	ALB = 1_008,
	AND = 1_020,
	ARE = 1_784,
	ARG = 1_032,
	ARM = 1_051,
	ASM = 1_016,
	ATA = 1_010,
	ATF = 1_260,
	ATG = 1_028,
	AUS = 1_036,
	AUT = 1_040,
	AZE = 1_031,
	BDI = 1_108,
	BEL = 1_056,
	BEN = 1_204,
	BES = 1_535,
	BFA = 1_854,
	BGD = 1_050,
	BGR = 1_100,
	BHR = 1_048,
	BHS = 1_044,
	BIH = 1_070,
	BLM = 1_652,
	BLR = 1_112,
	BLZ = 1_084,
	BMU = 1_060,
	BOL = 1_068,
	BRA = 1_076,
	BRB = 1_052,
	BRN = 1_096,
	BTN = 1_064,
	BVT = 1_074,
	BWA = 1_072,
	CAF = 1_140,
	CAN = 1_124,
	CCK = 1_166,
	CHE = 1_756,
	CHL = 1_152,
	CHN = 1_156,
	CIV = 1_384,
	CMR = 1_120,
	COD = 1_180,
	COG = 1_178,
	COK = 1_184,
	COL = 1_170,
	COM = 1_174,
	CPV = 1_132,
	CRI = 1_188,
	CUB = 1_192,
	CUW = 1_531,
	CXR = 1_162,
	CYM = 1_136,
	CYP = 1_196,
	CZE = 1_203,
	DEU = 1_276,
	DJI = 1_262,
	DMA = 1_212,
	DNK = 1_208,
	DOM = 1_214,
	DZA = 1_012,
	ECU = 1_218,
	EGY = 1_818,
	ERI = 1_232,
	ESH = 1_732,
	ESP = 1_724,
	EST = 1_233,
	ETH = 1_231,
	FIN = 1_246,
	FJI = 1_242,
	FLK = 1_238,
	FRA = 1_250,
	FRO = 1_234,
	FSM = 1_583,
	GAB = 1_266,
	GBR = 1_826,
	GEO = 1_268,
	GGY = 1_831,
	GHA = 1_288,
	GIB = 1_292,
	GIN = 1_324,
	GLP = 1_312,
	GMB = 1_270,
	GNB = 1_624,
	GNQ = 1_226,
	GRC = 1_300,
	GRD = 1_308,
	GRL = 1_304,
	GTM = 1_320,
	GUF = 1_254,
	GUM = 1_316,
	GUY = 1_328,
	HKG = 1_344,
	HMD = 1_334,
	HND = 1_340,
	HRV = 1_191,
	HTI = 1_332,
	HUN = 1_348,
	IDN = 1_360,
	IMN = 1_833,
	IND = 1_356,
	IOT = 1_086,
	IRL = 1_372,
	IRN = 1_364,
	IRQ = 1_368,
	ISL = 1_352,
	ISR = 1_376,
	ITA = 1_380,
	JAM = 1_388,
	JEY = 1_832,
	JOR = 1_400,
	JPN = 1_392,
	KAZ = 1_398,
	KEN = 1_404,
	KGZ = 1_417,
	KHM = 1_116,
	KIR = 1_296,
	KNA = 1_659,
	KOR = 1_410,
	KWT = 1_414,
	LAO = 1_418,
	LBN = 1_422,
	LBR = 1_430,
	LBY = 1_434,
	LCA = 1_662,
	LIE = 1_438,
	LKA = 1_144,
	LSO = 1_426,
	LTU = 1_440,
	LUX = 1_442,
	LVA = 1_428,
	MAC = 1_446,
	MAF = 1_663,
	MAR = 1_504,
	MCO = 1_492,
	MDA = 1_498,
	MDG = 1_450,
	MDV = 1_462,
	MEX = 1_484,
	MHL = 1_584,
	MKD = 1_807,
	MLI = 1_466,
	MLT = 1_470,
	MMR = 1_104,
	MNE = 1_499,
	MNG = 1_496,
	MNP = 1_580,
	MOZ = 1_508,
	MRT = 1_478,
	MSR = 1_500,
	MTQ = 1_474,
	MUS = 1_480,
	MWI = 1_454,
	MYS = 1_458,
	MYT = 1_175,
	NAM = 1_516,
	NCL = 1_540,
	NER = 1_562,
	NFK = 1_574,
	NGA = 1_566,
	NIC = 1_558,
	NIU = 1_570,
	NLD = 1_528,
	NOR = 1_578,
	NPL = 1_524,
	NRU = 1_520,
	NZL = 1_554,
	OMN = 1_512,
	PAK = 1_586,
	PAN = 1_591,
	PCN = 1_612,
	PER = 1_604,
	PHL = 1_608,
	PLW = 1_585,
	PNG = 1_598,
	POL = 1_616,
	PRI = 1_630,
	PRK = 1_408,
	PRT = 1_620,
	PRY = 1_600,
	PSE = 1_275,
	PYF = 1_258,
	QAT = 1_634,
	REU = 1_638,
	ROU = 1_642,
	RUS = 1_643,
	RWA = 1_646,
	SAU = 1_682,
	SDN = 1_729,
	SEN = 1_686,
	SGP = 1_702,
	SGS = 1_239,
	SHN = 1_654,
	SJM = 1_744,
	SLB = 1_090,
	SLE = 1_694,
	SLV = 1_222,
	SMR = 1_674,
	SOM = 1_706,
	SPM = 1_666,
	SRB = 1_688,
	SSD = 1_728,
	STP = 1_678,
	SUR = 1_740,
	SVK = 1_703,
	SVN = 1_705,
	SWE = 1_752,
	SWZ = 1_748,
	SXM = 1_534,
	SYC = 1_690,
	SYR = 1_760,
	TCA = 1_796,
	TCD = 1_148,
	TGO = 1_768,
	THA = 1_764,
	TJK = 1_762,
	TKL = 1_772,
	TKM = 1_795,
	TLS = 1_626,
	TON = 1_776,
	TTO = 1_780,
	TUN = 1_788,
	TUR = 1_792,
	TUV = 1_798,
	TWN = 1_158,
	TZA = 1_834,
	UGA = 1_800,
	UKR = 1_804,
	UMI = 1_581,
	URY = 1_858,
	USA = 1_840,
	UZB = 1_860,
	VAT = 1_336,
	VCT = 1_670,
	VEN = 1_862,
	VGB = 1_092,
	VIR = 1_850,
	VNM = 1_704,
	VUT = 1_548,
	WLF = 1_876,
	WSM = 1_882,
	YEM = 1_887,
	ZAF = 1_710,
	ZMB = 1_894,
	ZWE = 1_716,
}

impl CountryCode {
	//		as_str																
	/// Returns a string representation of the `CountryCode` variant.
	/// 
	/// This method provides a way to obtain a static string slice corresponding
	/// to a variant of the `CountryCode` enum. The returned string slice is
	/// suitable for use in scenarios where a string representation of the enum
	/// variant is needed, such as serialization or logging.
	/// 
	/// It is potentially different from the [`Display`] implementation, which
	/// returns a human-readable string representation of the enum variant, and
	/// the [`Debug`] implementation, which returns a string representation of
	/// the enum variant that is suitable for debugging purposes.
	/// 
	#[cfg_attr(    feature = "reasons",  allow(clippy::too_many_lines, reason = "Data not logic"))]
	#[cfg_attr(not(feature = "reasons"), allow(clippy::too_many_lines))]
	#[must_use]
	pub const fn as_str(&self) -> &'static str {
		match *self {
			//		Two-letter codes (ISO 3166-1 alpha-2)						
			Self::AD  => "AD",
			Self::AE  => "AE",
			Self::AF  => "AF",
			Self::AG  => "AG",
			Self::AI  => "AI",
			Self::AL  => "AL",
			Self::AM  => "AM",
			Self::AO  => "AO",
			Self::AQ  => "AQ",
			Self::AR  => "AR",
			Self::AS  => "AS",
			Self::AT  => "AT",
			Self::AU  => "AU",
			Self::AW  => "AW",
			Self::AX  => "AX",
			Self::AZ  => "AZ",
			Self::BA  => "BA",
			Self::BB  => "BB",
			Self::BD  => "BD",
			Self::BE  => "BE",
			Self::BF  => "BF",
			Self::BG  => "BG",
			Self::BH  => "BH",
			Self::BI  => "BI",
			Self::BJ  => "BJ",
			Self::BL  => "BL",
			Self::BM  => "BM",
			Self::BN  => "BN",
			Self::BO  => "BO",
			Self::BQ  => "BQ",
			Self::BR  => "BR",
			Self::BS  => "BS",
			Self::BT  => "BT",
			Self::BV  => "BV",
			Self::BW  => "BW",
			Self::BY  => "BY",
			Self::BZ  => "BZ",
			Self::CA  => "CA",
			Self::CC  => "CC",
			Self::CD  => "CD",
			Self::CF  => "CF",
			Self::CG  => "CG",
			Self::CH  => "CH",
			Self::CI  => "CI",
			Self::CK  => "CK",
			Self::CL  => "CL",
			Self::CM  => "CM",
			Self::CN  => "CN",
			Self::CO  => "CO",
			Self::CR  => "CR",
			Self::CU  => "CU",
			Self::CV  => "CV",
			Self::CW  => "CW",
			Self::CX  => "CX",
			Self::CY  => "CY",
			Self::CZ  => "CZ",
			Self::DE  => "DE",
			Self::DJ  => "DJ",
			Self::DK  => "DK",
			Self::DM  => "DM",
			Self::DO  => "DO",
			Self::DZ  => "DZ",
			Self::EC  => "EC",
			Self::EE  => "EE",
			Self::EG  => "EG",
			Self::EH  => "EH",
			Self::ER  => "ER",
			Self::ES  => "ES",
			Self::ET  => "ET",
			Self::FI  => "FI",
			Self::FJ  => "FJ",
			Self::FK  => "FK",
			Self::FM  => "FM",
			Self::FO  => "FO",
			Self::FR  => "FR",
			Self::GA  => "GA",
			Self::GB  => "GB",
			Self::GD  => "GD",
			Self::GE  => "GE",
			Self::GF  => "GF",
			Self::GG  => "GG",
			Self::GH  => "GH",
			Self::GI  => "GI",
			Self::GL  => "GL",
			Self::GM  => "GM",
			Self::GN  => "GN",
			Self::GP  => "GP",
			Self::GQ  => "GQ",
			Self::GR  => "GR",
			Self::GS  => "GS",
			Self::GT  => "GT",
			Self::GU  => "GU",
			Self::GW  => "GW",
			Self::GY  => "GY",
			Self::HK  => "HK",
			Self::HM  => "HM",
			Self::HN  => "HN",
			Self::HR  => "HR",
			Self::HT  => "HT",
			Self::HU  => "HU",
			Self::ID  => "ID",
			Self::IE  => "IE",
			Self::IL  => "IL",
			Self::IM  => "IM",
			Self::IN  => "IN",
			Self::IO  => "IO",
			Self::IQ  => "IQ",
			Self::IR  => "IR",
			Self::IS  => "IS",
			Self::IT  => "IT",
			Self::JE  => "JE",
			Self::JM  => "JM",
			Self::JO  => "JO",
			Self::JP  => "JP",
			Self::KE  => "KE",
			Self::KG  => "KG",
			Self::KH  => "KH",
			Self::KI  => "KI",
			Self::KM  => "KM",
			Self::KN  => "KN",
			Self::KP  => "KP",
			Self::KR  => "KR",
			Self::KW  => "KW",
			Self::KY  => "KY",
			Self::KZ  => "KZ",
			Self::LA  => "LA",
			Self::LB  => "LB",
			Self::LC  => "LC",
			Self::LI  => "LI",
			Self::LK  => "LK",
			Self::LR  => "LR",
			Self::LS  => "LS",
			Self::LT  => "LT",
			Self::LU  => "LU",
			Self::LV  => "LV",
			Self::LY  => "LY",
			Self::MA  => "MA",
			Self::MC  => "MC",
			Self::MD  => "MD",
			Self::ME  => "ME",
			Self::MF  => "MF",
			Self::MG  => "MG",
			Self::MH  => "MH",
			Self::MK  => "MK",
			Self::ML  => "ML",
			Self::MM  => "MM",
			Self::MN  => "MN",
			Self::MO  => "MO",
			Self::MP  => "MP",
			Self::MQ  => "MQ",
			Self::MR  => "MR",
			Self::MS  => "MS",
			Self::MT  => "MT",
			Self::MU  => "MU",
			Self::MV  => "MV",
			Self::MW  => "MW",
			Self::MX  => "MX",
			Self::MY  => "MY",
			Self::MZ  => "MZ",
			Self::NA  => "NA",
			Self::NC  => "NC",
			Self::NE  => "NE",
			Self::NF  => "NF",
			Self::NG  => "NG",
			Self::NI  => "NI",
			Self::NL  => "NL",
			Self::NO  => "NO",
			Self::NP  => "NP",
			Self::NR  => "NR",
			Self::NU  => "NU",
			Self::NZ  => "NZ",
			Self::OM  => "OM",
			Self::PA  => "PA",
			Self::PE  => "PE",
			Self::PF  => "PF",
			Self::PG  => "PG",
			Self::PH  => "PH",
			Self::PK  => "PK",
			Self::PL  => "PL",
			Self::PM  => "PM",
			Self::PN  => "PN",
			Self::PR  => "PR",
			Self::PS  => "PS",
			Self::PT  => "PT",
			Self::PW  => "PW",
			Self::PY  => "PY",
			Self::QA  => "QA",
			Self::RE  => "RE",
			Self::RO  => "RO",
			Self::RS  => "RS",
			Self::RU  => "RU",
			Self::RW  => "RW",
			Self::SA  => "SA",
			Self::SB  => "SB",
			Self::SC  => "SC",
			Self::SD  => "SD",
			Self::SE  => "SE",
			Self::SG  => "SG",
			Self::SH  => "SH",
			Self::SI  => "SI",
			Self::SJ  => "SJ",
			Self::SK  => "SK",
			Self::SL  => "SL",
			Self::SM  => "SM",
			Self::SN  => "SN",
			Self::SO  => "SO",
			Self::SR  => "SR",
			Self::SS  => "SS",
			Self::ST  => "ST",
			Self::SV  => "SV",
			Self::SX  => "SX",
			Self::SY  => "SY",
			Self::SZ  => "SZ",
			Self::TC  => "TC",
			Self::TD  => "TD",
			Self::TF  => "TF",
			Self::TG  => "TG",
			Self::TH  => "TH",
			Self::TJ  => "TJ",
			Self::TK  => "TK",
			Self::TL  => "TL",
			Self::TM  => "TM",
			Self::TN  => "TN",
			Self::TO  => "TO",
			Self::TR  => "TR",
			Self::TT  => "TT",
			Self::TV  => "TV",
			Self::TW  => "TW",
			Self::TZ  => "TZ",
			Self::UA  => "UA",
			Self::UG  => "UG",
			Self::UM  => "UM",
			Self::US  => "US",
			Self::UY  => "UY",
			Self::UZ  => "UZ",
			Self::VA  => "VA",
			Self::VC  => "VC",
			Self::VE  => "VE",
			Self::VG  => "VG",
			Self::VI  => "VI",
			Self::VN  => "VN",
			Self::VU  => "VU",
			Self::WF  => "WF",
			Self::WS  => "WS",
			Self::YE  => "YE",
			Self::YT  => "YT",
			Self::ZA  => "ZA",
			Self::ZM  => "ZM",
			Self::ZW  => "ZW",
			//		Three-letter codes (ISO 3166-1 alpha-3)						
			Self::ABW => "ABW",
			Self::AFG => "AFG",
			Self::AGO => "AGO",
			Self::AIA => "AIA",
			Self::ALA => "ALA",
			Self::ALB => "ALB",
			Self::AND => "AND",
			Self::ARE => "ARE",
			Self::ARG => "ARG",
			Self::ARM => "ARM",
			Self::ASM => "ASM",
			Self::ATA => "ATA",
			Self::ATF => "ATF",
			Self::ATG => "ATG",
			Self::AUS => "AUS",
			Self::AUT => "AUT",
			Self::AZE => "AZE",
			Self::BDI => "BDI",
			Self::BEL => "BEL",
			Self::BEN => "BEN",
			Self::BES => "BES",
			Self::BFA => "BFA",
			Self::BGD => "BGD",
			Self::BGR => "BGR",
			Self::BHR => "BHR",
			Self::BHS => "BHS",
			Self::BIH => "BIH",
			Self::BLM => "BLM",
			Self::BLR => "BLR",
			Self::BLZ => "BLZ",
			Self::BMU => "BMU",
			Self::BOL => "BOL",
			Self::BRA => "BRA",
			Self::BRB => "BRB",
			Self::BRN => "BRN",
			Self::BTN => "BTN",
			Self::BVT => "BVT",
			Self::BWA => "BWA",
			Self::CAF => "CAF",
			Self::CAN => "CAN",
			Self::CCK => "CCK",
			Self::CHE => "CHE",
			Self::CHL => "CHL",
			Self::CHN => "CHN",
			Self::CIV => "CIV",
			Self::CMR => "CMR",
			Self::COD => "COD",
			Self::COG => "COG",
			Self::COK => "COK",
			Self::COL => "COL",
			Self::COM => "COM",
			Self::CPV => "CPV",
			Self::CRI => "CRI",
			Self::CUB => "CUB",
			Self::CUW => "CUW",
			Self::CXR => "CXR",
			Self::CYM => "CYM",
			Self::CYP => "CYP",
			Self::CZE => "CZE",
			Self::DEU => "DEU",
			Self::DJI => "DJI",
			Self::DMA => "DMA",
			Self::DNK => "DNK",
			Self::DOM => "DOM",
			Self::DZA => "DZA",
			Self::ECU => "ECU",
			Self::EGY => "EGY",
			Self::ERI => "ERI",
			Self::ESH => "ESH",
			Self::ESP => "ESP",
			Self::EST => "EST",
			Self::ETH => "ETH",
			Self::FIN => "FIN",
			Self::FJI => "FJI",
			Self::FLK => "FLK",
			Self::FRA => "FRA",
			Self::FRO => "FRO",
			Self::FSM => "FSM",
			Self::GAB => "GAB",
			Self::GBR => "GBR",
			Self::GEO => "GEO",
			Self::GGY => "GGY",
			Self::GHA => "GHA",
			Self::GIB => "GIB",
			Self::GIN => "GIN",
			Self::GLP => "GLP",
			Self::GMB => "GMB",
			Self::GNB => "GNB",
			Self::GNQ => "GNQ",
			Self::GRC => "GRC",
			Self::GRD => "GRD",
			Self::GRL => "GRL",
			Self::GTM => "GTM",
			Self::GUF => "GUF",
			Self::GUM => "GUM",
			Self::GUY => "GUY",
			Self::HKG => "HKG",
			Self::HMD => "HMD",
			Self::HND => "HND",
			Self::HRV => "HRV",
			Self::HTI => "HTI",
			Self::HUN => "HUN",
			Self::IDN => "IDN",
			Self::IMN => "IMN",
			Self::IND => "IND",
			Self::IOT => "IOT",
			Self::IRL => "IRL",
			Self::IRN => "IRN",
			Self::IRQ => "IRQ",
			Self::ISL => "ISL",
			Self::ISR => "ISR",
			Self::ITA => "ITA",
			Self::JAM => "JAM",
			Self::JEY => "JEY",
			Self::JOR => "JOR",
			Self::JPN => "JPN",
			Self::KAZ => "KAZ",
			Self::KEN => "KEN",
			Self::KGZ => "KGZ",
			Self::KHM => "KHM",
			Self::KIR => "KIR",
			Self::KNA => "KNA",
			Self::KOR => "KOR",
			Self::KWT => "KWT",
			Self::LAO => "LAO",
			Self::LBN => "LBN",
			Self::LBR => "LBR",
			Self::LBY => "LBY",
			Self::LCA => "LCA",
			Self::LIE => "LIE",
			Self::LKA => "LKA",
			Self::LSO => "LSO",
			Self::LTU => "LTU",
			Self::LUX => "LUX",
			Self::LVA => "LVA",
			Self::MAC => "MAC",
			Self::MAF => "MAF",
			Self::MAR => "MAR",
			Self::MCO => "MCO",
			Self::MDA => "MDA",
			Self::MDG => "MDG",
			Self::MDV => "MDV",
			Self::MEX => "MEX",
			Self::MHL => "MHL",
			Self::MKD => "MKD",
			Self::MLI => "MLI",
			Self::MLT => "MLT",
			Self::MMR => "MMR",
			Self::MNE => "MNE",
			Self::MNG => "MNG",
			Self::MNP => "MNP",
			Self::MOZ => "MOZ",
			Self::MRT => "MRT",
			Self::MSR => "MSR",
			Self::MTQ => "MTQ",
			Self::MUS => "MUS",
			Self::MWI => "MWI",
			Self::MYS => "MYS",
			Self::MYT => "MYT",
			Self::NAM => "NAM",
			Self::NCL => "NCL",
			Self::NER => "NER",
			Self::NFK => "NFK",
			Self::NGA => "NGA",
			Self::NIC => "NIC",
			Self::NIU => "NIU",
			Self::NLD => "NLD",
			Self::NOR => "NOR",
			Self::NPL => "NPL",
			Self::NRU => "NRU",
			Self::NZL => "NZL",
			Self::OMN => "OMN",
			Self::PAK => "PAK",
			Self::PAN => "PAN",
			Self::PCN => "PCN",
			Self::PER => "PER",
			Self::PHL => "PHL",
			Self::PLW => "PLW",
			Self::PNG => "PNG",
			Self::POL => "POL",
			Self::PRI => "PRI",
			Self::PRK => "PRK",
			Self::PRT => "PRT",
			Self::PRY => "PRY",
			Self::PSE => "PSE",
			Self::PYF => "PYF",
			Self::QAT => "QAT",
			Self::REU => "REU",
			Self::ROU => "ROU",
			Self::RUS => "RUS",
			Self::RWA => "RWA",
			Self::SAU => "SAU",
			Self::SDN => "SDN",
			Self::SEN => "SEN",
			Self::SGP => "SGP",
			Self::SGS => "SGS",
			Self::SHN => "SHN",
			Self::SJM => "SJM",
			Self::SLB => "SLB",
			Self::SLE => "SLE",
			Self::SLV => "SLV",
			Self::SMR => "SMR",
			Self::SOM => "SOM",
			Self::SPM => "SPM",
			Self::SRB => "SRB",
			Self::SSD => "SSD",
			Self::STP => "STP",
			Self::SUR => "SUR",
			Self::SVK => "SVK",
			Self::SVN => "SVN",
			Self::SWE => "SWE",
			Self::SWZ => "SWZ",
			Self::SXM => "SXM",
			Self::SYC => "SYC",
			Self::SYR => "SYR",
			Self::TCA => "TCA",
			Self::TCD => "TCD",
			Self::TGO => "TGO",
			Self::THA => "THA",
			Self::TJK => "TJK",
			Self::TKL => "TKL",
			Self::TKM => "TKM",
			Self::TLS => "TLS",
			Self::TON => "TON",
			Self::TTO => "TTO",
			Self::TUN => "TUN",
			Self::TUR => "TUR",
			Self::TUV => "TUV",
			Self::TWN => "TWN",
			Self::TZA => "TZA",
			Self::UGA => "UGA",
			Self::UKR => "UKR",
			Self::UMI => "UMI",
			Self::URY => "URY",
			Self::USA => "USA",
			Self::UZB => "UZB",
			Self::VAT => "VAT",
			Self::VCT => "VCT",
			Self::VEN => "VEN",
			Self::VGB => "VGB",
			Self::VIR => "VIR",
			Self::VNM => "VNM",
			Self::VUT => "VUT",
			Self::WLF => "WLF",
			Self::WSM => "WSM",
			Self::YEM => "YEM",
			Self::ZAF => "ZAF",
			Self::ZMB => "ZMB",
			Self::ZWE => "ZWE",
		}
	}
}

impl Display for CountryCode {
	//		fmt																	
	fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
		write!(f, "{}", self.as_str())
	}
}

impl From<CountryCode> for u16 {
	//		from																
	fn from(code: CountryCode) -> Self {
		//	For maximum ease of use, both two-letter and three-letter codes are
		//	stored in the same enum. However, this causes a collision between the
		//	numeric representations. To avoid this, the three-letter codes have
		//	1,000 added to them, for the sole purpose of internal storage. This
		//	needs to be adjusted when the enum variants are serialized or otherwise
		//	represented as an integer.
		#[cfg_attr(    feature = "reasons",  allow(clippy::arithmetic_side_effects, reason = "Range is controlled"))]
		#[cfg_attr(not(feature = "reasons"), allow(clippy::arithmetic_side_effects))]
		if code as Self > 1_000 {
			code as Self - 1_000
		} else {
			code as Self
		}
	}
}

impl From<CountryCode> for String {
	//		from																
	fn from(code: CountryCode) -> Self {
		code.to_string()
	}
}

impl FromStr for CountryCode {
	type Err = String;
	
	//		from_str															
	#[cfg_attr(    feature = "reasons",  allow(clippy::too_many_lines, reason = "Data not logic"))]
	#[cfg_attr(not(feature = "reasons"), allow(clippy::too_many_lines))]
	fn from_str(s: &str) -> Result<Self, Self::Err> {
		match s.to_uppercase().as_str() {
			//		Two-letter codes (ISO 3166-1 alpha-2)						
			"AD"  => Ok(Self::AD),
			"AE"  => Ok(Self::AE),
			"AF"  => Ok(Self::AF),
			"AG"  => Ok(Self::AG),
			"AI"  => Ok(Self::AI),
			"AL"  => Ok(Self::AL),
			"AM"  => Ok(Self::AM),
			"AO"  => Ok(Self::AO),
			"AQ"  => Ok(Self::AQ),
			"AR"  => Ok(Self::AR),
			"AS"  => Ok(Self::AS),
			"AT"  => Ok(Self::AT),
			"AU"  => Ok(Self::AU),
			"AW"  => Ok(Self::AW),
			"AX"  => Ok(Self::AX),
			"AZ"  => Ok(Self::AZ),
			"BA"  => Ok(Self::BA),
			"BB"  => Ok(Self::BB),
			"BD"  => Ok(Self::BD),
			"BE"  => Ok(Self::BE),
			"BF"  => Ok(Self::BF),
			"BG"  => Ok(Self::BG),
			"BH"  => Ok(Self::BH),
			"BI"  => Ok(Self::BI),
			"BJ"  => Ok(Self::BJ),
			"BL"  => Ok(Self::BL),
			"BM"  => Ok(Self::BM),
			"BN"  => Ok(Self::BN),
			"BO"  => Ok(Self::BO),
			"BQ"  => Ok(Self::BQ),
			"BR"  => Ok(Self::BR),
			"BS"  => Ok(Self::BS),
			"BT"  => Ok(Self::BT),
			"BV"  => Ok(Self::BV),
			"BW"  => Ok(Self::BW),
			"BY"  => Ok(Self::BY),
			"BZ"  => Ok(Self::BZ),
			"CA"  => Ok(Self::CA),
			"CC"  => Ok(Self::CC),
			"CD"  => Ok(Self::CD),
			"CF"  => Ok(Self::CF),
			"CG"  => Ok(Self::CG),
			"CH"  => Ok(Self::CH),
			"CI"  => Ok(Self::CI),
			"CK"  => Ok(Self::CK),
			"CL"  => Ok(Self::CL),
			"CM"  => Ok(Self::CM),
			"CN"  => Ok(Self::CN),
			"CO"  => Ok(Self::CO),
			"CR"  => Ok(Self::CR),
			"CU"  => Ok(Self::CU),
			"CV"  => Ok(Self::CV),
			"CW"  => Ok(Self::CW),
			"CX"  => Ok(Self::CX),
			"CY"  => Ok(Self::CY),
			"CZ"  => Ok(Self::CZ),
			"DE"  => Ok(Self::DE),
			"DJ"  => Ok(Self::DJ),
			"DK"  => Ok(Self::DK),
			"DM"  => Ok(Self::DM),
			"DO"  => Ok(Self::DO),
			"DZ"  => Ok(Self::DZ),
			"EC"  => Ok(Self::EC),
			"EE"  => Ok(Self::EE),
			"EG"  => Ok(Self::EG),
			"EH"  => Ok(Self::EH),
			"ER"  => Ok(Self::ER),
			"ES"  => Ok(Self::ES),
			"ET"  => Ok(Self::ET),
			"FI"  => Ok(Self::FI),
			"FJ"  => Ok(Self::FJ),
			"FK"  => Ok(Self::FK),
			"FM"  => Ok(Self::FM),
			"FO"  => Ok(Self::FO),
			"FR"  => Ok(Self::FR),
			"GA"  => Ok(Self::GA),
			"GB"  => Ok(Self::GB),
			"GD"  => Ok(Self::GD),
			"GE"  => Ok(Self::GE),
			"GF"  => Ok(Self::GF),
			"GG"  => Ok(Self::GG),
			"GH"  => Ok(Self::GH),
			"GI"  => Ok(Self::GI),
			"GL"  => Ok(Self::GL),
			"GM"  => Ok(Self::GM),
			"GN"  => Ok(Self::GN),
			"GP"  => Ok(Self::GP),
			"GQ"  => Ok(Self::GQ),
			"GR"  => Ok(Self::GR),
			"GS"  => Ok(Self::GS),
			"GT"  => Ok(Self::GT),
			"GU"  => Ok(Self::GU),
			"GW"  => Ok(Self::GW),
			"GY"  => Ok(Self::GY),
			"HK"  => Ok(Self::HK),
			"HM"  => Ok(Self::HM),
			"HN"  => Ok(Self::HN),
			"HR"  => Ok(Self::HR),
			"HT"  => Ok(Self::HT),
			"HU"  => Ok(Self::HU),
			"ID"  => Ok(Self::ID),
			"IE"  => Ok(Self::IE),
			"IL"  => Ok(Self::IL),
			"IM"  => Ok(Self::IM),
			"IN"  => Ok(Self::IN),
			"IO"  => Ok(Self::IO),
			"IQ"  => Ok(Self::IQ),
			"IR"  => Ok(Self::IR),
			"IS"  => Ok(Self::IS),
			"IT"  => Ok(Self::IT),
			"JE"  => Ok(Self::JE),
			"JM"  => Ok(Self::JM),
			"JO"  => Ok(Self::JO),
			"JP"  => Ok(Self::JP),
			"KE"  => Ok(Self::KE),
			"KG"  => Ok(Self::KG),
			"KH"  => Ok(Self::KH),
			"KI"  => Ok(Self::KI),
			"KM"  => Ok(Self::KM),
			"KN"  => Ok(Self::KN),
			"KP"  => Ok(Self::KP),
			"KR"  => Ok(Self::KR),
			"KW"  => Ok(Self::KW),
			"KY"  => Ok(Self::KY),
			"KZ"  => Ok(Self::KZ),
			"LA"  => Ok(Self::LA),
			"LB"  => Ok(Self::LB),
			"LC"  => Ok(Self::LC),
			"LI"  => Ok(Self::LI),
			"LK"  => Ok(Self::LK),
			"LR"  => Ok(Self::LR),
			"LS"  => Ok(Self::LS),
			"LT"  => Ok(Self::LT),
			"LU"  => Ok(Self::LU),
			"LV"  => Ok(Self::LV),
			"LY"  => Ok(Self::LY),
			"MA"  => Ok(Self::MA),
			"MC"  => Ok(Self::MC),
			"MD"  => Ok(Self::MD),
			"ME"  => Ok(Self::ME),
			"MF"  => Ok(Self::MF),
			"MG"  => Ok(Self::MG),
			"MH"  => Ok(Self::MH),
			"MK"  => Ok(Self::MK),
			"ML"  => Ok(Self::ML),
			"MM"  => Ok(Self::MM),
			"MN"  => Ok(Self::MN),
			"MO"  => Ok(Self::MO),
			"MP"  => Ok(Self::MP),
			"MQ"  => Ok(Self::MQ),
			"MR"  => Ok(Self::MR),
			"MS"  => Ok(Self::MS),
			"MT"  => Ok(Self::MT),
			"MU"  => Ok(Self::MU),
			"MV"  => Ok(Self::MV),
			"MW"  => Ok(Self::MW),
			"MX"  => Ok(Self::MX),
			"MY"  => Ok(Self::MY),
			"MZ"  => Ok(Self::MZ),
			"NA"  => Ok(Self::NA),
			"NC"  => Ok(Self::NC),
			"NE"  => Ok(Self::NE),
			"NF"  => Ok(Self::NF),
			"NG"  => Ok(Self::NG),
			"NI"  => Ok(Self::NI),
			"NL"  => Ok(Self::NL),
			"NO"  => Ok(Self::NO),
			"NP"  => Ok(Self::NP),
			"NR"  => Ok(Self::NR),
			"NU"  => Ok(Self::NU),
			"NZ"  => Ok(Self::NZ),
			"OM"  => Ok(Self::OM),
			"PA"  => Ok(Self::PA),
			"PE"  => Ok(Self::PE),
			"PF"  => Ok(Self::PF),
			"PG"  => Ok(Self::PG),
			"PH"  => Ok(Self::PH),
			"PK"  => Ok(Self::PK),
			"PL"  => Ok(Self::PL),
			"PM"  => Ok(Self::PM),
			"PN"  => Ok(Self::PN),
			"PR"  => Ok(Self::PR),
			"PS"  => Ok(Self::PS),
			"PT"  => Ok(Self::PT),
			"PW"  => Ok(Self::PW),
			"PY"  => Ok(Self::PY),
			"QA"  => Ok(Self::QA),
			"RE"  => Ok(Self::RE),
			"RO"  => Ok(Self::RO),
			"RS"  => Ok(Self::RS),
			"RU"  => Ok(Self::RU),
			"RW"  => Ok(Self::RW),
			"SA"  => Ok(Self::SA),
			"SB"  => Ok(Self::SB),
			"SC"  => Ok(Self::SC),
			"SD"  => Ok(Self::SD),
			"SE"  => Ok(Self::SE),
			"SG"  => Ok(Self::SG),
			"SH"  => Ok(Self::SH),
			"SI"  => Ok(Self::SI),
			"SJ"  => Ok(Self::SJ),
			"SK"  => Ok(Self::SK),
			"SL"  => Ok(Self::SL),
			"SM"  => Ok(Self::SM),
			"SN"  => Ok(Self::SN),
			"SO"  => Ok(Self::SO),
			"SR"  => Ok(Self::SR),
			"SS"  => Ok(Self::SS),
			"ST"  => Ok(Self::ST),
			"SV"  => Ok(Self::SV),
			"SX"  => Ok(Self::SX),
			"SY"  => Ok(Self::SY),
			"SZ"  => Ok(Self::SZ),
			"TC"  => Ok(Self::TC),
			"TD"  => Ok(Self::TD),
			"TF"  => Ok(Self::TF),
			"TG"  => Ok(Self::TG),
			"TH"  => Ok(Self::TH),
			"TJ"  => Ok(Self::TJ),
			"TK"  => Ok(Self::TK),
			"TL"  => Ok(Self::TL),
			"TM"  => Ok(Self::TM),
			"TN"  => Ok(Self::TN),
			"TO"  => Ok(Self::TO),
			"TR"  => Ok(Self::TR),
			"TT"  => Ok(Self::TT),
			"TV"  => Ok(Self::TV),
			"TW"  => Ok(Self::TW),
			"TZ"  => Ok(Self::TZ),
			"UA"  => Ok(Self::UA),
			"UG"  => Ok(Self::UG),
			"UM"  => Ok(Self::UM),
			"US"  => Ok(Self::US),
			"UY"  => Ok(Self::UY),
			"UZ"  => Ok(Self::UZ),
			"VA"  => Ok(Self::VA),
			"VC"  => Ok(Self::VC),
			"VE"  => Ok(Self::VE),
			"VG"  => Ok(Self::VG),
			"VI"  => Ok(Self::VI),
			"VN"  => Ok(Self::VN),
			"VU"  => Ok(Self::VU),
			"WF"  => Ok(Self::WF),
			"WS"  => Ok(Self::WS),
			"YE"  => Ok(Self::YE),
			"YT"  => Ok(Self::YT),
			"ZA"  => Ok(Self::ZA),
			"ZM"  => Ok(Self::ZM),
			"ZW"  => Ok(Self::ZW),
			//		Three-letter codes (ISO 3166-1 alpha-3)						
			"ABW" => Ok(Self::ABW),
			"AFG" => Ok(Self::AFG),
			"AGO" => Ok(Self::AGO),
			"AIA" => Ok(Self::AIA),
			"ALA" => Ok(Self::ALA),
			"ALB" => Ok(Self::ALB),
			"AND" => Ok(Self::AND),
			"ARE" => Ok(Self::ARE),
			"ARG" => Ok(Self::ARG),
			"ARM" => Ok(Self::ARM),
			"ASM" => Ok(Self::ASM),
			"ATA" => Ok(Self::ATA),
			"ATF" => Ok(Self::ATF),
			"ATG" => Ok(Self::ATG),
			"AUS" => Ok(Self::AUS),
			"AUT" => Ok(Self::AUT),
			"AZE" => Ok(Self::AZE),
			"BDI" => Ok(Self::BDI),
			"BEL" => Ok(Self::BEL),
			"BEN" => Ok(Self::BEN),
			"BES" => Ok(Self::BES),
			"BFA" => Ok(Self::BFA),
			"BGD" => Ok(Self::BGD),
			"BGR" => Ok(Self::BGR),
			"BHR" => Ok(Self::BHR),
			"BHS" => Ok(Self::BHS),
			"BIH" => Ok(Self::BIH),
			"BLM" => Ok(Self::BLM),
			"BLR" => Ok(Self::BLR),
			"BLZ" => Ok(Self::BLZ),
			"BMU" => Ok(Self::BMU),
			"BOL" => Ok(Self::BOL),
			"BRA" => Ok(Self::BRA),
			"BRB" => Ok(Self::BRB),
			"BRN" => Ok(Self::BRN),
			"BTN" => Ok(Self::BTN),
			"BVT" => Ok(Self::BVT),
			"BWA" => Ok(Self::BWA),
			"CAF" => Ok(Self::CAF),
			"CAN" => Ok(Self::CAN),
			"CCK" => Ok(Self::CCK),
			"CHE" => Ok(Self::CHE),
			"CHL" => Ok(Self::CHL),
			"CHN" => Ok(Self::CHN),
			"CIV" => Ok(Self::CIV),
			"CMR" => Ok(Self::CMR),
			"COD" => Ok(Self::COD),
			"COG" => Ok(Self::COG),
			"COK" => Ok(Self::COK),
			"COL" => Ok(Self::COL),
			"COM" => Ok(Self::COM),
			"CPV" => Ok(Self::CPV),
			"CRI" => Ok(Self::CRI),
			"CUB" => Ok(Self::CUB),
			"CUW" => Ok(Self::CUW),
			"CXR" => Ok(Self::CXR),
			"CYM" => Ok(Self::CYM),
			"CYP" => Ok(Self::CYP),
			"CZE" => Ok(Self::CZE),
			"DEU" => Ok(Self::DEU),
			"DJI" => Ok(Self::DJI),
			"DMA" => Ok(Self::DMA),
			"DNK" => Ok(Self::DNK),
			"DOM" => Ok(Self::DOM),
			"DZA" => Ok(Self::DZA),
			"ECU" => Ok(Self::ECU),
			"EGY" => Ok(Self::EGY),
			"ERI" => Ok(Self::ERI),
			"ESH" => Ok(Self::ESH),
			"ESP" => Ok(Self::ESP),
			"EST" => Ok(Self::EST),
			"ETH" => Ok(Self::ETH),
			"FIN" => Ok(Self::FIN),
			"FJI" => Ok(Self::FJI),
			"FLK" => Ok(Self::FLK),
			"FRA" => Ok(Self::FRA),
			"FRO" => Ok(Self::FRO),
			"FSM" => Ok(Self::FSM),
			"GAB" => Ok(Self::GAB),
			"GBR" => Ok(Self::GBR),
			"GEO" => Ok(Self::GEO),
			"GGY" => Ok(Self::GGY),
			"GHA" => Ok(Self::GHA),
			"GIB" => Ok(Self::GIB),
			"GIN" => Ok(Self::GIN),
			"GLP" => Ok(Self::GLP),
			"GMB" => Ok(Self::GMB),
			"GNB" => Ok(Self::GNB),
			"GNQ" => Ok(Self::GNQ),
			"GRC" => Ok(Self::GRC),
			"GRD" => Ok(Self::GRD),
			"GRL" => Ok(Self::GRL),
			"GTM" => Ok(Self::GTM),
			"GUF" => Ok(Self::GUF),
			"GUM" => Ok(Self::GUM),
			"GUY" => Ok(Self::GUY),
			"HKG" => Ok(Self::HKG),
			"HMD" => Ok(Self::HMD),
			"HND" => Ok(Self::HND),
			"HRV" => Ok(Self::HRV),
			"HTI" => Ok(Self::HTI),
			"HUN" => Ok(Self::HUN),
			"IDN" => Ok(Self::IDN),
			"IMN" => Ok(Self::IMN),
			"IND" => Ok(Self::IND),
			"IOT" => Ok(Self::IOT),
			"IRL" => Ok(Self::IRL),
			"IRN" => Ok(Self::IRN),
			"IRQ" => Ok(Self::IRQ),
			"ISL" => Ok(Self::ISL),
			"ISR" => Ok(Self::ISR),
			"ITA" => Ok(Self::ITA),
			"JAM" => Ok(Self::JAM),
			"JEY" => Ok(Self::JEY),
			"JOR" => Ok(Self::JOR),
			"JPN" => Ok(Self::JPN),
			"KAZ" => Ok(Self::KAZ),
			"KEN" => Ok(Self::KEN),
			"KGZ" => Ok(Self::KGZ),
			"KHM" => Ok(Self::KHM),
			"KIR" => Ok(Self::KIR),
			"KNA" => Ok(Self::KNA),
			"KOR" => Ok(Self::KOR),
			"KWT" => Ok(Self::KWT),
			"LAO" => Ok(Self::LAO),
			"LBN" => Ok(Self::LBN),
			"LBR" => Ok(Self::LBR),
			"LBY" => Ok(Self::LBY),
			"LCA" => Ok(Self::LCA),
			"LIE" => Ok(Self::LIE),
			"LKA" => Ok(Self::LKA),
			"LSO" => Ok(Self::LSO),
			"LTU" => Ok(Self::LTU),
			"LUX" => Ok(Self::LUX),
			"LVA" => Ok(Self::LVA),
			"MAC" => Ok(Self::MAC),
			"MAF" => Ok(Self::MAF),
			"MAR" => Ok(Self::MAR),
			"MCO" => Ok(Self::MCO),
			"MDA" => Ok(Self::MDA),
			"MDG" => Ok(Self::MDG),
			"MDV" => Ok(Self::MDV),
			"MEX" => Ok(Self::MEX),
			"MHL" => Ok(Self::MHL),
			"MKD" => Ok(Self::MKD),
			"MLI" => Ok(Self::MLI),
			"MLT" => Ok(Self::MLT),
			"MMR" => Ok(Self::MMR),
			"MNE" => Ok(Self::MNE),
			"MNG" => Ok(Self::MNG),
			"MNP" => Ok(Self::MNP),
			"MOZ" => Ok(Self::MOZ),
			"MRT" => Ok(Self::MRT),
			"MSR" => Ok(Self::MSR),
			"MTQ" => Ok(Self::MTQ),
			"MUS" => Ok(Self::MUS),
			"MWI" => Ok(Self::MWI),
			"MYS" => Ok(Self::MYS),
			"MYT" => Ok(Self::MYT),
			"NAM" => Ok(Self::NAM),
			"NCL" => Ok(Self::NCL),
			"NER" => Ok(Self::NER),
			"NFK" => Ok(Self::NFK),
			"NGA" => Ok(Self::NGA),
			"NIC" => Ok(Self::NIC),
			"NIU" => Ok(Self::NIU),
			"NLD" => Ok(Self::NLD),
			"NOR" => Ok(Self::NOR),
			"NPL" => Ok(Self::NPL),
			"NRU" => Ok(Self::NRU),
			"NZL" => Ok(Self::NZL),
			"OMN" => Ok(Self::OMN),
			"PAK" => Ok(Self::PAK),
			"PAN" => Ok(Self::PAN),
			"PCN" => Ok(Self::PCN),
			"PER" => Ok(Self::PER),
			"PHL" => Ok(Self::PHL),
			"PLW" => Ok(Self::PLW),
			"PNG" => Ok(Self::PNG),
			"POL" => Ok(Self::POL),
			"PRI" => Ok(Self::PRI),
			"PRK" => Ok(Self::PRK),
			"PRT" => Ok(Self::PRT),
			"PRY" => Ok(Self::PRY),
			"PSE" => Ok(Self::PSE),
			"PYF" => Ok(Self::PYF),
			"QAT" => Ok(Self::QAT),
			"REU" => Ok(Self::REU),
			"ROU" => Ok(Self::ROU),
			"RUS" => Ok(Self::RUS),
			"RWA" => Ok(Self::RWA),
			"SAU" => Ok(Self::SAU),
			"SDN" => Ok(Self::SDN),
			"SEN" => Ok(Self::SEN),
			"SGP" => Ok(Self::SGP),
			"SGS" => Ok(Self::SGS),
			"SHN" => Ok(Self::SHN),
			"SJM" => Ok(Self::SJM),
			"SLB" => Ok(Self::SLB),
			"SLE" => Ok(Self::SLE),
			"SLV" => Ok(Self::SLV),
			"SMR" => Ok(Self::SMR),
			"SOM" => Ok(Self::SOM),
			"SPM" => Ok(Self::SPM),
			"SRB" => Ok(Self::SRB),
			"SSD" => Ok(Self::SSD),
			"STP" => Ok(Self::STP),
			"SUR" => Ok(Self::SUR),
			"SVK" => Ok(Self::SVK),
			"SVN" => Ok(Self::SVN),
			"SWE" => Ok(Self::SWE),
			"SWZ" => Ok(Self::SWZ),
			"SXM" => Ok(Self::SXM),
			"SYC" => Ok(Self::SYC),
			"SYR" => Ok(Self::SYR),
			"TCA" => Ok(Self::TCA),
			"TCD" => Ok(Self::TCD),
			"TGO" => Ok(Self::TGO),
			"THA" => Ok(Self::THA),
			"TJK" => Ok(Self::TJK),
			"TKL" => Ok(Self::TKL),
			"TKM" => Ok(Self::TKM),
			"TLS" => Ok(Self::TLS),
			"TON" => Ok(Self::TON),
			"TTO" => Ok(Self::TTO),
			"TUN" => Ok(Self::TUN),
			"TUR" => Ok(Self::TUR),
			"TUV" => Ok(Self::TUV),
			"TWN" => Ok(Self::TWN),
			"TZA" => Ok(Self::TZA),
			"UGA" => Ok(Self::UGA),
			"UKR" => Ok(Self::UKR),
			"UMI" => Ok(Self::UMI),
			"URY" => Ok(Self::URY),
			"USA" => Ok(Self::USA),
			"UZB" => Ok(Self::UZB),
			"VAT" => Ok(Self::VAT),
			"VCT" => Ok(Self::VCT),
			"VEN" => Ok(Self::VEN),
			"VGB" => Ok(Self::VGB),
			"VIR" => Ok(Self::VIR),
			"VNM" => Ok(Self::VNM),
			"VUT" => Ok(Self::VUT),
			"WLF" => Ok(Self::WLF),
			"WSM" => Ok(Self::WSM),
			"YEM" => Ok(Self::YEM),
			"ZAF" => Ok(Self::ZAF),
			"ZMB" => Ok(Self::ZMB),
			"ZWE" => Ok(Self::ZWE),
			//		Invalid														
			_     => Err(format!("Invalid CountryCode: {s}")),
		}
	}
}

#[cfg_attr(    feature = "reasons",  allow(clippy::zero_prefixed_literal, reason = "Zeroes aid readability here"))]
#[cfg_attr(not(feature = "reasons"), allow(clippy::zero_prefixed_literal))]
impl TryFrom<u16> for CountryCode {
	type Error = String;
	
	//		try_from															
	#[cfg_attr(    feature = "reasons",  allow(clippy::too_many_lines, reason = "Data not logic"))]
	#[cfg_attr(not(feature = "reasons"), allow(clippy::too_many_lines))]
	fn try_from(value: u16) -> Result<Self, Self::Error> {
		match value {
			//		Two-letter codes (ISO 3166-1 alpha-2)								
			//	The two-letter codes are chosen in preference to the three-letter codes
			//	when converting from numerical representation.
			004 => Ok(Self::AF),
			008 => Ok(Self::AL),
			010 => Ok(Self::AQ),
			012 => Ok(Self::DZ),
			016 => Ok(Self::AS),
			020 => Ok(Self::AD),
			024 => Ok(Self::AO),
			028 => Ok(Self::AG),
			031 => Ok(Self::AZ),
			032 => Ok(Self::AR),
			036 => Ok(Self::AU),
			040 => Ok(Self::AT),
			044 => Ok(Self::BS),
			048 => Ok(Self::BH),
			050 => Ok(Self::BD),
			051 => Ok(Self::AM),
			052 => Ok(Self::BB),
			056 => Ok(Self::BE),
			060 => Ok(Self::BM),
			064 => Ok(Self::BT),
			068 => Ok(Self::BO),
			070 => Ok(Self::BA),
			072 => Ok(Self::BW),
			074 => Ok(Self::BV),
			076 => Ok(Self::BR),
			084 => Ok(Self::BZ),
			086 => Ok(Self::IO),
			090 => Ok(Self::SB),
			092 => Ok(Self::VG),
			096 => Ok(Self::BN),
			100 => Ok(Self::BG),
			104 => Ok(Self::MM),
			108 => Ok(Self::BI),
			112 => Ok(Self::BY),
			116 => Ok(Self::KH),
			120 => Ok(Self::CM),
			124 => Ok(Self::CA),
			132 => Ok(Self::CV),
			136 => Ok(Self::KY),
			140 => Ok(Self::CF),
			144 => Ok(Self::LK),
			148 => Ok(Self::TD),
			152 => Ok(Self::CL),
			156 => Ok(Self::CN),
			158 => Ok(Self::TW),
			162 => Ok(Self::CX),
			166 => Ok(Self::CC),
			170 => Ok(Self::CO),
			174 => Ok(Self::KM),
			175 => Ok(Self::YT),
			178 => Ok(Self::CG),
			180 => Ok(Self::CD),
			184 => Ok(Self::CK),
			188 => Ok(Self::CR),
			191 => Ok(Self::HR),
			192 => Ok(Self::CU),
			196 => Ok(Self::CY),
			203 => Ok(Self::CZ),
			204 => Ok(Self::BJ),
			208 => Ok(Self::DK),
			212 => Ok(Self::DM),
			214 => Ok(Self::DO),
			218 => Ok(Self::EC),
			222 => Ok(Self::SV),
			226 => Ok(Self::GQ),
			231 => Ok(Self::ET),
			232 => Ok(Self::ER),
			233 => Ok(Self::EE),
			234 => Ok(Self::FO),
			238 => Ok(Self::FK),
			239 => Ok(Self::GS),
			242 => Ok(Self::FJ),
			246 => Ok(Self::FI),
			248 => Ok(Self::AX),
			250 => Ok(Self::FR),
			254 => Ok(Self::GF),
			258 => Ok(Self::PF),
			260 => Ok(Self::TF),
			262 => Ok(Self::DJ),
			266 => Ok(Self::GA),
			268 => Ok(Self::GE),
			270 => Ok(Self::GM),
			275 => Ok(Self::PS),
			276 => Ok(Self::DE),
			288 => Ok(Self::GH),
			292 => Ok(Self::GI),
			296 => Ok(Self::KI),
			300 => Ok(Self::GR),
			304 => Ok(Self::GL),
			308 => Ok(Self::GD),
			312 => Ok(Self::GP),
			316 => Ok(Self::GU),
			320 => Ok(Self::GT),
			324 => Ok(Self::GN),
			328 => Ok(Self::GY),
			332 => Ok(Self::HT),
			334 => Ok(Self::HM),
			336 => Ok(Self::VA),
			340 => Ok(Self::HN),
			344 => Ok(Self::HK),
			348 => Ok(Self::HU),
			352 => Ok(Self::IS),
			356 => Ok(Self::IN),
			360 => Ok(Self::ID),
			364 => Ok(Self::IR),
			368 => Ok(Self::IQ),
			372 => Ok(Self::IE),
			376 => Ok(Self::IL),
			380 => Ok(Self::IT),
			384 => Ok(Self::CI),
			388 => Ok(Self::JM),
			392 => Ok(Self::JP),
			398 => Ok(Self::KZ),
			400 => Ok(Self::JO),
			404 => Ok(Self::KE),
			408 => Ok(Self::KP),
			410 => Ok(Self::KR),
			414 => Ok(Self::KW),
			417 => Ok(Self::KG),
			418 => Ok(Self::LA),
			422 => Ok(Self::LB),
			426 => Ok(Self::LS),
			428 => Ok(Self::LV),
			430 => Ok(Self::LR),
			434 => Ok(Self::LY),
			438 => Ok(Self::LI),
			440 => Ok(Self::LT),
			442 => Ok(Self::LU),
			446 => Ok(Self::MO),
			450 => Ok(Self::MG),
			454 => Ok(Self::MW),
			458 => Ok(Self::MY),
			462 => Ok(Self::MV),
			466 => Ok(Self::ML),
			470 => Ok(Self::MT),
			474 => Ok(Self::MQ),
			478 => Ok(Self::MR),
			480 => Ok(Self::MU),
			484 => Ok(Self::MX),
			492 => Ok(Self::MC),
			496 => Ok(Self::MN),
			498 => Ok(Self::MD),
			499 => Ok(Self::ME),
			500 => Ok(Self::MS),
			504 => Ok(Self::MA),
			508 => Ok(Self::MZ),
			512 => Ok(Self::OM),
			516 => Ok(Self::NA),
			520 => Ok(Self::NR),
			524 => Ok(Self::NP),
			528 => Ok(Self::NL),
			531 => Ok(Self::CW),
			533 => Ok(Self::AW),
			534 => Ok(Self::SX),
			535 => Ok(Self::BQ),
			540 => Ok(Self::NC),
			548 => Ok(Self::VU),
			554 => Ok(Self::NZ),
			558 => Ok(Self::NI),
			562 => Ok(Self::NE),
			566 => Ok(Self::NG),
			570 => Ok(Self::NU),
			574 => Ok(Self::NF),
			578 => Ok(Self::NO),
			580 => Ok(Self::MP),
			581 => Ok(Self::UM),
			583 => Ok(Self::FM),
			584 => Ok(Self::MH),
			585 => Ok(Self::PW),
			586 => Ok(Self::PK),
			591 => Ok(Self::PA),
			598 => Ok(Self::PG),
			600 => Ok(Self::PY),
			604 => Ok(Self::PE),
			608 => Ok(Self::PH),
			612 => Ok(Self::PN),
			616 => Ok(Self::PL),
			620 => Ok(Self::PT),
			624 => Ok(Self::GW),
			626 => Ok(Self::TL),
			630 => Ok(Self::PR),
			634 => Ok(Self::QA),
			638 => Ok(Self::RE),
			642 => Ok(Self::RO),
			643 => Ok(Self::RU),
			646 => Ok(Self::RW),
			652 => Ok(Self::BL),
			654 => Ok(Self::SH),
			659 => Ok(Self::KN),
			660 => Ok(Self::AI),
			662 => Ok(Self::LC),
			663 => Ok(Self::MF),
			666 => Ok(Self::PM),
			670 => Ok(Self::VC),
			674 => Ok(Self::SM),
			678 => Ok(Self::ST),
			682 => Ok(Self::SA),
			686 => Ok(Self::SN),
			688 => Ok(Self::RS),
			690 => Ok(Self::SC),
			694 => Ok(Self::SL),
			702 => Ok(Self::SG),
			703 => Ok(Self::SK),
			704 => Ok(Self::VN),
			705 => Ok(Self::SI),
			706 => Ok(Self::SO),
			710 => Ok(Self::ZA),
			716 => Ok(Self::ZW),
			724 => Ok(Self::ES),
			728 => Ok(Self::SS),
			729 => Ok(Self::SD),
			732 => Ok(Self::EH),
			740 => Ok(Self::SR),
			744 => Ok(Self::SJ),
			748 => Ok(Self::SZ),
			752 => Ok(Self::SE),
			756 => Ok(Self::CH),
			760 => Ok(Self::SY),
			762 => Ok(Self::TJ),
			764 => Ok(Self::TH),
			768 => Ok(Self::TG),
			772 => Ok(Self::TK),
			776 => Ok(Self::TO),
			780 => Ok(Self::TT),
			784 => Ok(Self::AE),
			788 => Ok(Self::TN),
			792 => Ok(Self::TR),
			795 => Ok(Self::TM),
			796 => Ok(Self::TC),
			798 => Ok(Self::TV),
			800 => Ok(Self::UG),
			804 => Ok(Self::UA),
			807 => Ok(Self::MK),
			818 => Ok(Self::EG),
			826 => Ok(Self::GB),
			831 => Ok(Self::GG),
			832 => Ok(Self::JE),
			833 => Ok(Self::IM),
			834 => Ok(Self::TZ),
			840 => Ok(Self::US),
			850 => Ok(Self::VI),
			854 => Ok(Self::BF),
			858 => Ok(Self::UY),
			860 => Ok(Self::UZ),
			862 => Ok(Self::VE),
			876 => Ok(Self::WF),
			882 => Ok(Self::WS),
			887 => Ok(Self::YE),
			894 => Ok(Self::ZM),
			//		Three-letter codes (ISO 3166-1 alpha-3)						
			//	As both the two-letter and three-letter codes have the same numerical
			//	representation, there is no specific number that will lead to a three-
			//	letter code being produced. The two-letter codes are chosen in
			//	preference, and are considered to be equivalent.
			//		Invalid														
			_   => Err(format!("Invalid CountryCode: {value}")),
		}
	}
}

impl TryFrom<String> for CountryCode {
	type Error = String;
	
	//		try_from															
	fn try_from(value: String) -> Result<Self, Self::Error> {
		value.as_str().parse()
	}
}




//		Structs

//		Country																	
/// A country.
/// 
/// A country has a number of properties, including a name, a country code, the
/// currencies it uses, and the languages used in it.
/// 
/// Each country is identified by a country code, which can be expressed as two
/// or three letters or three numbers, as defined by the ISO 3166-1 standard.
/// 
/// # Data sources
/// 
/// The list of codes and other country information is available from
/// [the ISO site](https://www.iso.org/iso-3166-country-codes.html), and from
/// [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1).
/// 
/// # See also
/// 
/// * [`CountryCode`]
/// 
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize, ToSchema)]
#[non_exhaustive]
pub struct Country {
	//		Public properties													
	/// The name of the country.
	pub name:       String,
	
	/// The country code. For more information, see [`CountryCode`].
	pub code:       CountryCode,
	
	/// The currencies used in the country.
	pub currencies: HashSet<CurrencyCode>,
	
	/// The languages spoken in the country.
	pub languages:  HashSet<LanguageCode>,
}


